# Generated by Django 3.2.24 on 2024-05-07 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='full_name',
            new_name='name',
        ),
    ]
