# Generated by Django 3.2.24 on 2024-05-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_full_name_delivery_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.IntegerField(choices=[(0, 'ordered'), (1, 'delivered')]),
        ),
    ]
