# Generated by Django 3.2.24 on 2024-05-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_delivery_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.IntegerField(choices=[(0, 'ordered'), (1, 'delivered')], null=True),
        ),
    ]
