# Generated by Django 3.2.24 on 2024-05-07 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_delivery_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='delivery_date',
            new_name='order_date',
        ),
    ]
