# Generated by Django 3.2.24 on 2024-05-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_rename_delivery_date_delivery_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.IntegerField(choices=[(0, 'ordered'), (1, 'delivered')], default=0, null=True),
        ),
    ]
