# Generated by Django 3.2.24 on 2024-07-15 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
