# Generated by Django 3.2.24 on 2024-03-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20240308_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_history',
            name='quantity',
            field=models.IntegerField(choices=[(0, 'zero'), (1, 'one'), (2, 'two'), (3, 'three'), (4, 'four')], default=0),
        ),
    ]
