# Generated by Django 3.2.24 on 2024-04-22 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='customer',
            new_name='user',
        ),
    ]
