# Generated by Django 3.2.24 on 2024-05-07 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20240506_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_history',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order_history',
            name='product',
        ),
        migrations.DeleteModel(
            name='delivery',
        ),
        migrations.DeleteModel(
            name='Order_history',
        ),
    ]
